#!/usr/bin/env python3
"""
Create WebSocket API Gateway endpoints from a CSV configuration file.

Author:       Arnold Ramos
Date Created: 2026

Python port of CreateApiGateway.ps1 (PIM WebSocket provisioning).

For each row in the input CSV this script creates a WEBSOCKET API with three
routes ($connect, $disconnect, ping), their integrations and responses, a
"production" stage, and a deployment. The resulting WebSocket URLs are printed
as a table at the end of the run, and added to the GitHub job summary when one
is available. Nothing is written to disk.

Credentials are resolved by the standard boto3 credential chain (environment
variables, AWS_PROFILE, ~/.aws/credentials, SSO cache, container credentials,
or an EC2 instance role). Nothing is passed explicitly.

Input CSV format:
    Name,Domain,Region
    pdpm1api-example,example.com,us-east-1

    Name   - API name, generated by normalize_requests.py
    Domain - Customer domain used to build the integration URI
    Region - AWS region ID (e.g. us-east-1), not a regional group code

Usage:
    python createapigw.py --config-file config.csv
"""

import argparse
import csv
import os
import sys
from pathlib import Path

import boto3
from botocore.exceptions import BotoCoreError, ClientError

# ============================================================
# CONFIGURATION
# ============================================================

ROUTE_KEYS = ["$connect", "$disconnect", "ping"]
API_STAGE = "production"
ROUTE_SELECTION_EXPRESSION = "$request.body.type"

# NOT escaped, unlike TEMPLATE_SELECTION_EXPRESSION below. CreateRoute rejects
# "\$default" with:
#     Currently, only $default is supported as a route response selection
#     expression.
# API Gateway accepts only the plain reserved word here — it is a fixed marker
# meaning "this route handles two-way communication", not a parsed expression.
ROUTE_RESPONSE_SELECTION_EXPRESSION = "$default"

# The backslash is required by API Gateway, not a leftover from PowerShell. In a
# selection expression '$' introduces a variable, so an unescaped "$default" is
# read as a variable named 'default' and AWS rejects it with:
#     Unexpected variable in selection expression: $default
# Escaping it as "\$default" means the literal reserved key. This was briefly
# "corrected" to "$default" during the port, which broke CreateIntegration.
# https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-selection-expressions.html
TEMPLATE_SELECTION_EXPRESSION = "\\$default"

INTEGRATION_RESPONSE_TEMPLATE_SELECTION = "${integration.response.statuscode}"

# Request templates (VTL) keyed by route. The inner "$default" key is the
# template selection expression AWS matches against.
REQUEST_TEMPLATES = {
    "$connect": {
        "$default": (
            '{"connectionID" : "$context.connectionId", '
            '"authCode" : "$input.params().querystring.auth" }'
        )
    },
    "$disconnect": {"$default": '{"connectionID" : "$context.connectionId"}'},
    # NOTE: the PowerShell script had '{ statusCode : 200}' - invalid JSON, the
    # key was unquoted, and a MOCK integration will not respond without valid
    # JSON here. Corrected to {"statusCode": 200}.
    "ping": {"$default": '{"statusCode": 200}'},
}

# Per-route integration settings. URIs are formatted with the row's domain.
INTEGRATION_CONFIG = {
    "$connect": {
        "IntegrationType": "HTTP",
        "IntegrationMethod": "POST",
        "UriTemplate": "https://{domain}/XWeb/Core/WebsocketModule.ashx?function=CompleteConnection",
    },
    "$disconnect": {
        "IntegrationType": "HTTP",
        "IntegrationMethod": "POST",
        "UriTemplate": "https://{domain}/XWeb/Core/WebsocketModule.ashx?function=CloseConnection",
    },
    "ping": {
        "IntegrationType": "MOCK",
        "IntegrationMethod": None,
        "UriTemplate": None,
    },
}

# Response templates applied only to specific routes
INTEGRATION_RESPONSE_TEMPLATES = {
    "ping": {"200": '{"type": "pong"}'},
}

OUTPUT_HEADER = ["API Name", "Domain", "Websocket URL"]

# Widths for the results table printed at the end of a run.
COLUMN_WIDTHS = [28, 32, 0]  # 0 = last column, not padded


# ============================================================
# HELPERS
# ============================================================

def log(message):
    """Write a message to stdout, flushed so output interleaves correctly."""
    print(message, flush=True)


def get_client(region, _cache={}):
    """Return a cached apigatewayv2 client for the given region."""
    if region not in _cache:
        _cache[region] = boto3.client("apigatewayv2", region_name=region)
    return _cache[region]


def format_row(values):
    """Pad a row into aligned columns for the results table."""
    cells = []
    for value, width in zip(values, COLUMN_WIDTHS):
        cells.append(str(value).ljust(width) if width else str(value))
    return "  ".join(cells).rstrip()


def print_results(created):
    """Print the created APIs as a table. Nothing is written to disk."""
    if not created:
        log("\nNo APIs were created.")
        return

    rule = "=" * 90
    log("")
    log(rule)
    log(format_row(OUTPUT_HEADER))
    log(rule)
    for row in created:
        log(format_row(row))
    log(rule)


def write_step_summary(created):
    """Add the same table to the GitHub job summary. No-op outside Actions."""
    summary_path = os.environ.get("GITHUB_STEP_SUMMARY")
    if not summary_path or not created:
        return
    with open(summary_path, "a", encoding="utf-8") as handle:
        handle.write("\n### Created APIs\n\n")
        handle.write("| " + " | ".join(OUTPUT_HEADER) + " |\n")
        handle.write("| " + " | ".join("---" for _ in OUTPUT_HEADER) + " |\n")
        for name, domain, url in created:
            handle.write(f"| `{name}` | {domain} | `{url}` |\n")


# ============================================================
# API CREATION
# ============================================================

def create_integrations(client, api_id, api_domain):
    """Create one integration per route. Returns {route_key: integration_id}."""
    integration_ids = {}
    for route_key in ROUTE_KEYS:
        config = INTEGRATION_CONFIG[route_key]
        params = {
            "ApiId": api_id,
            "IntegrationType": config["IntegrationType"],
            "TemplateSelectionExpression": TEMPLATE_SELECTION_EXPRESSION,
            "RequestTemplates": REQUEST_TEMPLATES[route_key],
        }
        if config["IntegrationMethod"]:
            params["IntegrationMethod"] = config["IntegrationMethod"]
        if config["UriTemplate"]:
            params["IntegrationUri"] = config["UriTemplate"].format(domain=api_domain)

        response = client.create_integration(**params)
        integration_ids[route_key] = response["IntegrationId"]
        log(f"    Integration created for {route_key}: {response['IntegrationId']}")
    return integration_ids


def create_integration_responses(client, api_id, integration_ids):
    """Create the $default integration response for each integration."""
    for route_key in ROUTE_KEYS:
        params = {
            "ApiId": api_id,
            "IntegrationId": integration_ids[route_key],
            "IntegrationResponseKey": "$default",
            "TemplateSelectionExpression": INTEGRATION_RESPONSE_TEMPLATE_SELECTION,
        }
        if route_key in INTEGRATION_RESPONSE_TEMPLATES:
            params["ResponseTemplates"] = INTEGRATION_RESPONSE_TEMPLATES[route_key]

        client.create_integration_response(**params)
        log(f"    Integration response created for {route_key}")


def create_routes(client, api_id, integration_ids):
    """Create one route per route key. Returns {route_key: route_id}."""
    route_ids = {}
    for route_key in ROUTE_KEYS:
        response = client.create_route(
            ApiId=api_id,
            RouteKey=route_key,
            RouteResponseSelectionExpression=ROUTE_RESPONSE_SELECTION_EXPRESSION,
            Target=f"integrations/{integration_ids[route_key]}",
        )
        route_ids[route_key] = response["RouteId"]
        log(f"    Route created for {route_key}: {response['RouteId']}")
    return route_ids


def create_route_responses(client, api_id, route_ids):
    """Create the $default route response for each route."""
    for route_key in ROUTE_KEYS:
        client.create_route_response(
            ApiId=api_id,
            RouteId=route_ids[route_key],
            RouteResponseKey="$default",
        )
        log(f"    Route response created for {route_key}")


def provision_api(api_name, api_domain, api_region):
    """Create and deploy a single WebSocket API. Returns the WebSocket URL."""
    client = get_client(api_region)

    log(f"  Creating WebSocket API in {api_region}...")
    api = client.create_api(
        Name=api_name,
        ProtocolType="WEBSOCKET",
        RouteSelectionExpression=ROUTE_SELECTION_EXPRESSION,
    )
    api_id = api["ApiId"]
    log(f"  API created: {api_id}")

    integration_ids = create_integrations(client, api_id, api_domain)
    create_integration_responses(client, api_id, integration_ids)
    route_ids = create_routes(client, api_id, integration_ids)
    create_route_responses(client, api_id, route_ids)

    client.create_stage(
        ApiId=api_id,
        StageName=API_STAGE,
        DefaultRouteSettings={"LoggingLevel": "ERROR"},
    )
    log(f"  Stage '{API_STAGE}' created")

    # Only deploy once every route was created successfully
    if len(route_ids) != len(ROUTE_KEYS):
        raise RuntimeError(
            f"Expected {len(ROUTE_KEYS)} routes but created {len(route_ids)}; skipping deployment"
        )

    client.create_deployment(ApiId=api_id, StageName=API_STAGE)
    log(f"  Deployed to stage '{API_STAGE}'")

    # create_api already returns ApiEndpoint, so no follow-up get_api is needed
    return api["ApiEndpoint"]


# ============================================================
# MAIN
# ============================================================

def main():
    parser = argparse.ArgumentParser(
        description="Create WebSocket API Gateway endpoints from a CSV configuration file."
    )
    parser.add_argument(
        "--config-file",
        required=True,
        help="Path to the CSV configuration file (columns: Name, Domain, Region)",
    )
    args = parser.parse_args()

    config_path = Path(args.config_file)
    if not config_path.is_file():
        log(f"ERROR: Configuration file not found: {config_path}")
        sys.exit(1)

    with config_path.open(newline="", encoding="utf-8-sig") as handle:
        rows = list(csv.DictReader(handle))

    if not rows:
        log(f"ERROR: No rows found in {config_path}")
        sys.exit(1)

    created = []
    failed = 0

    for row in rows:
        api_name = (row.get("Name") or "").strip()
        api_domain = (row.get("Domain") or "").strip()
        api_region = (row.get("Region") or "").strip()

        if not api_name:
            log(f"ERROR: Row missing Name in {config_path}. Skipping.")
            failed += 1
            continue

        # Skip the row if no Region was supplied, rather than defaulting to null
        if not api_region:
            log(f"ERROR: No Region specified for '{api_name}' in {config_path}. Skipping.")
            failed += 1
            continue

        log(f"===== Processing '{api_name}' ({api_domain}) in {api_region} =====")
        try:
            api_url = provision_api(api_name, api_domain, api_region)
            created.append([api_name, api_domain, api_url])
            log(f"SUCCESS: '{api_name}' -> {api_url}")
        except (ClientError, BotoCoreError, RuntimeError) as error:
            # A failure here may leave a partially built API in AWS - review before re-running,
            # since API Gateway permits duplicate API names and a retry will not resume.
            log(f"ERROR: Failed to create '{api_name}' in {api_region}: {error}")
            failed += 1

    print_results(created)
    write_step_summary(created)
    log(f"\nDone. {len(created)} succeeded, {failed} failed.")

    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()